---
apiVersion: v1
kind: Service
metadata:
  name: grumpy
  namespace: default
  labels:
    name: grumpy
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: grumpy 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grumpy
  namespace: default
  labels:
    name: grumpy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grumpy
  template:
    metadata:
      name: grumpy
      labels:
        name: grumpy
    spec:
      containers:
        - name: webhook
          image: quay.io/wangke19/grumpywebhook:latest
          imagePullPolicy: Always
          args:
            - -alsologtostderr
            - --log_dir=/
            - -v=10
            - 2>&1
          resources:
            limits:
              memory: 256Mi
              cpu: 300m
            requests:
              memory: 00Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: grumpy
        - name: logs
          emptyDir: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: grumpy
webhooks:
  - name: grumpy.giantswarm.io
    clientConfig:
      service:
        name: grumpy
        namespace: default
        url: "https://grumpy.default.apps.kewang-0113op1.qe.devcluster.openshift.com/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGekNDQXY4Q0ZBVCtmTHVqZGI3Zk8xWXFEalRWY1R6akJTL05NQTBHQ1NxR1NJYjNEUUVCRFFVQU1JSEgKTVFzd0NRWURWUVFHRXdKRVJURVFNQTRHQTFVRUNBd0hRMjlzYjJkdVpURVFNQTRHQTFVRUJ3d0hRMjlzYjJkdQpaVEVQTUEwR0ExVUVFUXdHTkRJME1qUXlNUlF3RWdZRFZRUUpEQXRJWVd4c2J5QWdNVFl5TVRFVE1CRUdBMVVFCkNnd0taMmxoYm5SemQyRnliVEVaTUJjR0ExVUVDd3dRUlcxdmFua2dSR1Z3WVhKMGJXVnVkREVXTUJRR0ExVUUKQXd3TloybGhiblJ6ZDJGeWJTNXBiekVsTUNNR0NTcUdTSWIzRFFFSkFSWVdibTh0Y21Wd2JIbEFaMmxoYm5SegpkMkZ5YlM1cGJ6QWVGdzB5TXpBNE1ERXdPVEl6TVRsYUZ3MHlNekE0TXpFd09USXpNVGxhTUlISE1Rc3dDUVlEClZRUUdFd0pFUlRFUU1BNEdBMVVFQ0F3SFEyOXNiMmR1WlRFUU1BNEdBMVVFQnd3SFEyOXNiMmR1WlRFUE1BMEcKQTFVRUVRd0dOREkwTWpReU1SUXdFZ1lEVlFRSkRBdElZV3hzYnlBZ01UWXlNVEVUTUJFR0ExVUVDZ3dLWjJsaApiblJ6ZDJGeWJURVpNQmNHQTFVRUN3d1FSVzF2YW5rZ1JHVndZWEowYldWdWRERVdNQlFHQTFVRUF3d05aMmxoCmJuUnpkMkZ5YlM1cGJ6RWxNQ01HQ1NxR1NJYjNEUUVKQVJZV2JtOHRjbVZ3YkhsQVoybGhiblJ6ZDJGeWJTNXAKYnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHIyRnlyNkxhZk9hRWMrV3lPcwo1M1V0TmM0MkY2ZlpLY01lOXJ0ZjJXSldEc3BOaDhCZWwvQStUSzlPSUxBQ0MwemdhQlU4QnJrZ0d3YlRTK3NlCmNZaTI5ZHRhdElVK0Y5em9VcUY5dHlMYmVURFJpWm0wck1SNGlpaGZ6amtiUGdPYkx6V29iVWRxR1lubmtXQzAKbjdGT2M5cVpIaHFOemU5NS9GTnJiMkM0bFdmaDJJWFl3Q2t4VG5JTVJkMlJDYk9LcW5qZ0xGdUJPSDYyRGQrTQpKZGkyZHhPQ3JNOE9ycGFFcEUyNkY1VVhtRlVZUE0vVUh6cDJvSGhxUzZxWWJXUmdOdGVtUElWNHRZNUpDU0l0CkFLRGRZVHNpKzN6VHB5SjdwVU1MbTBhUktQbjVNaktVOWhoUGlJWko2RmNjQzBBWnNtMjZkckx5MEJXZnBFZHYKbkNFQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVEwRkFBT0NBUUVBai9KTGtzbWUvMUd4MjFNQmliOHVXVkl2MGdOagpOcy9TWHFSVEZLTjNHcG9YZVc1ZGxIbXZzSUxieU92ZFAzY2NqbFRYTEl3QlZpQzI1UDM4YnNkZGV1V2h3NXdkCkd0WXllZmljK1d2bFg0Q3FxbkJvaVZkR1hIbU9JcW9yV3hIazNwSmNwTlZONUNFdXdiajFmaktGbC9naWgwR2sKTVJRK2lEUjVMQVkra3pMVGtqbjZSbmVCamFpTExOcEgvQXo0TSt2bW50amJ6aEZiRXJPb3BFRWtLQlcxUGdOMQpXTlUwZXdMT3VDQURzWHpYalJ3bjBiZ3dWN2ExRitaNWViWUF1d29pZ1lRK0Zoek1Yc0ZOdnhwVFRyUjJKUXNVCk9zRkZkeTVVdXRUMkxCN1JjRTQ4YnExbFFiQXY5SmNhRmp6S2dvcWRZdUJrL2haMGkySTJlMjJqMFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
